baseURL = "https://ynishizawa.com/"
languageCode = 'ja'
title = 'Nishizawa Pages | Cloudflare Guide'
defaultContentLanguage = 'ja' 
theme = 'clarity'
hasCJKLanguage = true
summaryLength = 50

[params]
  introDescription = """
  Cloudflareパートナー企業でCloudflareの導入・運用のサポートをしています西澤です。  
  インターネットセキュリティに関する様々な疑問を「もっと分かりやすく」伝えたくて、このブログを個人的に運営しています。  
  非エンジニアの視点で、わかりやすい言葉を心がけています。  
[ご連絡はこちら（Twitter）からどうぞ](https://twitter.com/ctO5lSnpzpWNOz5)
  """
  customJS = ["js/analytics.js"]
  
[params.sidebar]
  enable = true
  
[params.author]
  name = "Nishizawa"
  photo = "/images/avatar.jpg"

[params.social]
  twitter = "ctO5lSnpzpWNOz5"

[menu]
  [[menu.main]]
    name = "ホーム"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "投稿"
    url = "/post/"
    weight = 2